---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: crawler
    component: backend
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: backend
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "crawler.fullname" . }}
      labels:
        app: crawler
        component: backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: crawler
          env:
            - name: URL
              value: {{ .Values.app.URL }}
            - name: EXCLUDE_URLS
              value: {{ .Values.app.excludeUrls }}
            - name: MONGO
              value: {{ .Values.db.databaseHost |  default (printf "%s-mongodb" .Release.Name) }}
            - name: RMQ_HOST
              value: {{ .Values.rabbit.host | default (printf "%s-rabbitmq" .Release.Name) }}
            - name: RMQ_QUEUE
              value: {{ .Values.rabbit.queue }}
            - name: RMQ_USERNAME
              value: {{ .Values.rabbit.username }}
            - name: RMQ_PASSWORD
              value: {{ .Values.rabbit.password }}
            - name: CHECK_INTERVAL
              value: "3600"
