image: google/cloud-sdk:alpine

stages:
  - prepare_cluster
  - deploy_staging
  - deploy_production

before_script:
  - gcloud config set project $GOOGLE_PROJECT
  - gcloud auth activate-service-account --key-file $KEY_FILE

init_cluster_job:
  stage: prepare_cluster
  only:
    refs:
      - master
  when: manual
  script:
    - apk --no-cache --update add curl unzip
    - curl https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip --output tf.zip
    - unzip tf.zip -d /usr/bin/
    - cd infra/terraform
    - terraform init
    - terraform apply -input=false -auto-approve -var "project=$GOOGLE_PROJECT" -var "machine_type=$GOOGLE_MACHINE_TYPE"
    - cd ../..

deploy_staging_job:
  stage: deploy_staging
  only:
    refs:
      - develop
  script:
    - gcloud container clusters get-credentials crawler --zone europe-west1-b
    - sh ops/prepare.sh
    - kubectl apply -f kubernetes/namespaces/staging-ns.yml
    - kubectl config set-context --current --namespace staging
    - make run

deploy_production_job:
  stage: deploy_production
  only:
    refs:
      - master
  when: manual
  script:
    - gcloud container clusters get-credentials crawler --zone europe-west1-b
    - sh ops/prepare.sh
    - kubectl apply -f kubernetes/namespaces/production-ns.yml
    - kubectl config set-context --current --namespace production
    - make run
