apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
spec:
  rules:
    - host: crawler.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "ui.fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
