{
 "title": "Crawler metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" },
   {
    "name": "rate",
    "label": "Rate interval",
    "query": "1m,10m,30m,1h,4h,8h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.95" }
  ]
 },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Page Parse Time Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(crawler_page_parse_time_bucket{kubernetes_namespace=~\"$namespace\"}[$rate])) by (le))"
    }
   ]
  },
  {
   "title": "Parsed Pages Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_pages_parsed{kubernetes_namespace=~\"$namespace\"}[$rate])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Page Connection Time Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(crawler_site_connection_time_bucket{kubernetes_namespace=~\"$namespace\"}[$rate])) by (le))"
    }
   ]
  },
  {
   "title": "Pages Parsed by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(crawler_pages_parsed{kubernetes_namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "namespace" },
  {
   "title": "Served Pages Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_pages_served{kubernetes_namespace=~\"$namespace\"}[$rate])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Page Generation Time Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(web_page_gen_time_bucket{kubernetes_namespace=~\"$namespace\"}[$rate])) by (le))"
    }
   ]
  }
 ]
}